/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import TrabalhoFinal.Aluno;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Classe da tela para busca de alunos na lista
 * @author danielbricio
 */
public class BuscarAluno extends javax.swing.JDialog {
    
    private ArrayList<Aluno> listAlunos = new ArrayList<Aluno>();

    /**
     * Criar nova tela BuscarAluno
     * @param parent - Frame pai
     * @param modal - is a boolean of modal
     */
    public BuscarAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Criar nova tela BuscarAluno
     * @param parent - Frame pai
     * @param modal - is a boolean of modal
     * @param listAlunos - lista de alunos
     */
    public BuscarAluno(java.awt.Frame parent, boolean modal, ArrayList<Aluno> listAlunos) {
        super(parent, modal);
        initComponents();
        this.listAlunos = listAlunos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarAluno = new javax.swing.JLabel();
        jLabelNomeDoAluno = new javax.swing.JLabel();
        txtBuscarNomeAluno = new javax.swing.JTextField();
        jLabelMatriculaDoAluno = new javax.swing.JLabel();
        txtMatriculaConsultar = new javax.swing.JFormattedTextField();
        btnBuscarAluno = new javax.swing.JButton();
        btnVoltarAoMenuConsultar = new javax.swing.JButton();
        txtIdadeConsultar = new javax.swing.JFormattedTextField();
        jLabelIdadeConsultar = new javax.swing.JLabel();
        jLabelCpfConsultar = new javax.swing.JLabel();
        txtCpfConsultar = new javax.swing.JFormattedTextField();
        txtTelefoneConsultar = new javax.swing.JFormattedTextField();
        jLabelTelefoneConsultar = new javax.swing.JLabel();
        jLabelNascimentoConsultar = new javax.swing.JLabel();
        txtNascimentoConsultar = new javax.swing.JFormattedTextField();
        lblMenu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPorFavor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1020, 530));
        setSize(new java.awt.Dimension(1020, 530));

        jLabelConsultarAluno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelConsultarAluno.setForeground(new java.awt.Color(224, 30, 33));
        jLabelConsultarAluno.setText("Consultar Aluno");

        jLabelNomeDoAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeDoAluno.setForeground(new java.awt.Color(11, 111, 181));
        jLabelNomeDoAluno.setText("Nome do Aluno:");

        jLabelMatriculaDoAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMatriculaDoAluno.setForeground(new java.awt.Color(11, 111, 181));
        jLabelMatriculaDoAluno.setText("Matrícula:");

        try {
            txtMatriculaConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatriculaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarAluno.setBackground(new java.awt.Color(11, 111, 181));
        btnBuscarAluno.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBuscarAluno.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAluno.setText("Consultar Aluno");
        btnBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunoActionPerformed(evt);
            }
        });

        btnVoltarAoMenuConsultar.setBackground(new java.awt.Color(11, 111, 181));
        btnVoltarAoMenuConsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnVoltarAoMenuConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltarAoMenuConsultar.setText("Voltar ao menu principal");
        btnVoltarAoMenuConsultar.setActionCommand("Voltar ao menu principal");
        btnVoltarAoMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuConsultarActionPerformed(evt);
            }
        });

        try {
            txtIdadeConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIdadeConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelIdadeConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIdadeConsultar.setForeground(new java.awt.Color(11, 111, 181));
        jLabelIdadeConsultar.setText("Idade:");

        jLabelCpfConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCpfConsultar.setForeground(new java.awt.Color(11, 111, 181));
        jLabelCpfConsultar.setText("CPF:");

        try {
            txtCpfConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtTelefoneConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelTelefoneConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefoneConsultar.setForeground(new java.awt.Color(11, 111, 181));
        jLabelTelefoneConsultar.setText("Telefone:");

        jLabelNascimentoConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNascimentoConsultar.setForeground(new java.awt.Color(11, 111, 181));
        jLabelNascimentoConsultar.setText("Nascimento:");

        try {
            txtNascimentoConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblMenu.setFont(new java.awt.Font("Malgun Gothic", 1, 60)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(224, 30, 33));
        lblMenu.setText("Cadastre");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 111, 181));
        jLabel1.setText("™");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(11, 111, 181));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("_____________________________________________________________________________________________________________________________________________________");

        jLabelPorFavor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPorFavor.setForeground(new java.awt.Color(224, 30, 33));
        jLabelPorFavor.setText("Por favor, insira os dados solicitados para efetuar a buscar!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(jLabel1)
                                .addGap(499, 499, 499)
                                .addComponent(jLabelConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMenu)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addComponent(jLabelPorFavor, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabelNomeDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(txtBuscarNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabelMatriculaDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabelTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(txtMatriculaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jLabelNascimentoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(txtNascimentoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(btnBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(btnVoltarAoMenuConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelConsultarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3)))
                .addGap(6, 6, 6)
                .addComponent(jLabelPorFavor)
                .addGap(5, 5, 5)
                .addComponent(jLabelNomeDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBuscarNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMatriculaDoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatriculaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabelNascimentoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtNascimentoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnBuscarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVoltarAoMenuConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para ação do botão VOLTAR,
     * este irá fechar a tela e continuar o script do sistema.
     * @param evt - Evento de click no botão
     */
    private void btnVoltarAoMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuConsultarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnVoltarAoMenuConsultarActionPerformed

    /**
     * Método para ação do botão BUSCAR, 
     * e para toda a logica da busca de alunos
     * @param evt - Evento de click no botão
     */
    private void btnBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunoActionPerformed
        
        Aluno aluno = new Aluno();
        aluno.setMatricula(Integer.parseInt(txtMatriculaConsultar.getText()));
        aluno.setNome(txtBuscarNomeAluno.getText());
        aluno.setCpf(txtCpfConsultar.getText());
        aluno.setDataNascimento(txtNascimentoConsultar.getText());
        aluno.setTelefone(txtTelefoneConsultar.getText());
        aluno.setIdade(Integer.parseInt(txtIdadeConsultar.getText()));
        
        //verificar se ja esta na lista
         if(this.listAlunos.contains(aluno)){
            JOptionPane.showMessageDialog(null,"Aluno na Lista");
        }else JOptionPane.showMessageDialog(null, "Aluno não está na lista");
        this.dispose();
        
    }//GEN-LAST:event_btnBuscarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarAluno dialog = new BuscarAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAluno;
    private javax.swing.JButton btnVoltarAoMenuConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConsultarAluno;
    private javax.swing.JLabel jLabelCpfConsultar;
    private javax.swing.JLabel jLabelIdadeConsultar;
    private javax.swing.JLabel jLabelMatriculaDoAluno;
    private javax.swing.JLabel jLabelNascimentoConsultar;
    private javax.swing.JLabel jLabelNomeDoAluno;
    private javax.swing.JLabel jLabelPorFavor;
    private javax.swing.JLabel jLabelTelefoneConsultar;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JTextField txtBuscarNomeAluno;
    private javax.swing.JFormattedTextField txtCpfConsultar;
    private javax.swing.JFormattedTextField txtIdadeConsultar;
    private javax.swing.JFormattedTextField txtMatriculaConsultar;
    private javax.swing.JFormattedTextField txtNascimentoConsultar;
    private javax.swing.JFormattedTextField txtTelefoneConsultar;
    // End of variables declaration//GEN-END:variables
}
