/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import TrabalhoFinal.Aluno;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author danielbricio
 */
public class BuscarAluno extends javax.swing.JDialog {
    
    private ArrayList<Aluno> listAlunos = new ArrayList<Aluno>();

    public BuscarAluno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public BuscarAluno(java.awt.Frame parent, boolean modal, ArrayList<Aluno> listAlunos) {
        super(parent, modal);
        initComponents();
        this.listAlunos = listAlunos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarAluno = new javax.swing.JLabel();
        jLabelPorFavor = new javax.swing.JLabel();
        jLabelNomeDoAluno = new javax.swing.JLabel();
        txtBuscarNomeAluno = new javax.swing.JTextField();
        jLabelMatriculaDoAluno = new javax.swing.JLabel();
        txtMatriculaConsultar = new javax.swing.JFormattedTextField();
        btnBuscarAluno = new javax.swing.JButton();
        btnVoltarAoMenuConsultar = new javax.swing.JButton();
        txtIdadeConsultar = new javax.swing.JFormattedTextField();
        jLabelIdadeConsultar = new javax.swing.JLabel();
        jLabelCpfConsultar = new javax.swing.JLabel();
        txtCpfConsultar = new javax.swing.JFormattedTextField();
        txtTelefoneConsultar = new javax.swing.JFormattedTextField();
        jLabelTelefoneConsultar = new javax.swing.JLabel();
        jLabelNascimentoConsultar = new javax.swing.JLabel();
        txtNascimentoConsultar = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelConsultarAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelConsultarAluno.setText("Consultar Aluno");

        jLabelPorFavor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPorFavor.setText("Por favor, insira os dados solicitados para efetuar a buscar!");

        jLabelNomeDoAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeDoAluno.setText("Nome do Aluno:");

        jLabelMatriculaDoAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMatriculaDoAluno.setText("Matrícula:");

        try {
            txtMatriculaConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatriculaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnBuscarAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscarAluno.setText("Buscar Aluno");
        btnBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunoActionPerformed(evt);
            }
        });

        btnVoltarAoMenuConsultar.setText("Voltar ao menu ");
        btnVoltarAoMenuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarAoMenuConsultarActionPerformed(evt);
            }
        });

        try {
            txtIdadeConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIdadeConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelIdadeConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIdadeConsultar.setText("Idade:");

        jLabelCpfConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCpfConsultar.setText("CPF:");

        try {
            txtCpfConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        try {
            txtTelefoneConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelTelefoneConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefoneConsultar.setText("Telefone:");

        jLabelNascimentoConsultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNascimentoConsultar.setText("Nascimento:");

        try {
            txtNascimentoConsultar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimentoConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelNascimentoConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNascimentoConsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltarAoMenuConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatriculaConsultar)
                            .addComponent(jLabelMatriculaDoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIdadeConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdadeConsultar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCpfConsultar)
                            .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefoneConsultar)
                            .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)))
                    .addComponent(txtBuscarNomeAluno)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeDoAluno)
                            .addComponent(jLabelConsultarAluno)
                            .addComponent(jLabelPorFavor))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConsultarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPorFavor)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeDoAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelMatriculaDoAluno)
                                    .addComponent(jLabelIdadeConsultar)
                                    .addComponent(jLabelCpfConsultar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMatriculaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdadeConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelefoneConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefoneConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelNascimentoConsultar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNascimentoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltarAoMenuConsultar)))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarAoMenuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarAoMenuConsultarActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnVoltarAoMenuConsultarActionPerformed

    private void btnBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunoActionPerformed
        
        Aluno aluno = new Aluno();
        aluno.setMatricula(Integer.parseInt(txtMatriculaConsultar.getText()));
        aluno.setNome(txtBuscarNomeAluno.getText());
        aluno.setCpf(txtCpfConsultar.getText());
        aluno.setDataNascimento(txtNascimentoConsultar.getText());
        aluno.setTelefone(txtTelefoneConsultar.getText());
        aluno.setIdade(Integer.parseInt(txtIdadeConsultar.getText()));
        
        //verificar se ja esta na lista
         if(this.listAlunos.contains(aluno)){
            JOptionPane.showMessageDialog(null,"Aluno na Lista");
        }else JOptionPane.showMessageDialog(null, "Aluno não está na lista");
        this.dispose();
        
    }//GEN-LAST:event_btnBuscarAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarAluno dialog = new BuscarAluno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAluno;
    private javax.swing.JButton btnVoltarAoMenuConsultar;
    private javax.swing.JLabel jLabelConsultarAluno;
    private javax.swing.JLabel jLabelCpfConsultar;
    private javax.swing.JLabel jLabelIdadeConsultar;
    private javax.swing.JLabel jLabelMatriculaDoAluno;
    private javax.swing.JLabel jLabelNascimentoConsultar;
    private javax.swing.JLabel jLabelNomeDoAluno;
    private javax.swing.JLabel jLabelPorFavor;
    private javax.swing.JLabel jLabelTelefoneConsultar;
    private javax.swing.JTextField txtBuscarNomeAluno;
    private javax.swing.JFormattedTextField txtCpfConsultar;
    private javax.swing.JFormattedTextField txtIdadeConsultar;
    private javax.swing.JFormattedTextField txtMatriculaConsultar;
    private javax.swing.JFormattedTextField txtNascimentoConsultar;
    private javax.swing.JFormattedTextField txtTelefoneConsultar;
    // End of variables declaration//GEN-END:variables
}
