/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author Philipe
 */
public class Menu extends javax.swing.JDialog {

    /**
     * Creates new form Menu
     */
    public Menu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        jBtnCadastrar = new javax.swing.JButton();
        jBtnConsultar = new javax.swing.JButton();
        jBtnInserir = new javax.swing.JButton();
        jBtnObter3Aluno = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnObterPU = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnImprimirVelhoNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(200, 300));

        lblMenu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMenu.setText("MENU");

        jBtnCadastrar.setText("Cadastrar");
        jBtnCadastrar.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnCadastrar.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnCadastrar.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnConsultar.setText("Consultar Aluno");
        jBtnConsultar.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnConsultar.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnConsultar.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnInserir.setText("<html>\n<center>\nInserir na \n<br>\n3 pos\n</center>"); // NOI18N
        jBtnInserir.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnInserir.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnInserir.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnObter3Aluno.setText("<html> <center>Obter Aluno <br> 3 pos </center>"); // NOI18N
        jBtnObter3Aluno.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnObter3Aluno.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnObter3Aluno.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnRemover.setText("Remover (Ultimo)");
        jBtnRemover.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnRemover.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnRemover.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnObterPU.setText("<html> <center> Obter Matricula  <br> primeiro e ultimo </center>");
        jBtnObterPU.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnObterPU.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnObterPU.setPreferredSize(new java.awt.Dimension(125, 40));
        jBtnObterPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObterPUActionPerformed(evt);
            }
        });

        jBtnSalvar.setText("Salvar CSV");
        jBtnSalvar.setMaximumSize(new java.awt.Dimension(125, 40));
        jBtnSalvar.setMinimumSize(new java.awt.Dimension(125, 40));
        jBtnSalvar.setPreferredSize(new java.awt.Dimension(125, 40));

        jBtnImprimirVelhoNovo.setText("<html>\n<center>\nImprimir mais velho\n<br>\n e mais novo\n</center>");
        jBtnImprimirVelhoNovo.setPreferredSize(new java.awt.Dimension(125, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnImprimirVelhoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObterPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObter3Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenu)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnObter3Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnObterPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnImprimirVelhoNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnObterPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObterPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnObterPUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu dialog = new Menu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCadastrar;
    private javax.swing.JButton jBtnConsultar;
    private javax.swing.JButton jBtnImprimirVelhoNovo;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JButton jBtnObter3Aluno;
    private javax.swing.JButton jBtnObterPU;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
